paramètres :  buildConfiguration : 'Release'

steps:
- task: DotNetCoreCLI@2
 displayName : 'Construire le projet - ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'build'
 arguments : '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
 displayName : 'Publier le projet - ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
 arguments : '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}'
    zipAfterPublish: true